#!/usr/bin/env bash

# Installation:
#
# 1.   vim /etc/ssh/sshd_config 
#      PrintMotd no
#
# 2.   vim /etc/pam.d/login
#      # session optional pam_motd.so
#

GREEN='\033[1;32m'
BROWN='\033[0;36m'
NC='\033[0m'
ROOT=`df -Ph | grep 'centos-root' | awk '{print $4}' | tr -d '\n'`

MEMORY1=`free -t -m | grep "Mem" | awk '{print $6" MB";}'`
MEMORY2=`free -t -m | grep "Mem" | awk '{print $2" MB";}'`
PSA=`ps -Afl | wc -l`

#System uptime
uptime=`cat /proc/uptime | cut -f1 -d.`
upDays=$((uptime/60/60/24))
upHours=$((uptime/60/60%24))
upMins=$((uptime/60%60))
upSecs=$((uptime%60))

#System load
LOAD1=`cat /proc/loadavg | awk {'print $1'}`
LOAD5=`cat /proc/loadavg | awk {'print $2'}`
LOAD15=`cat /proc/loadavg | awk {'print $3'}`

echo -e "${GREEN}
 _______                   _______        __                                  
|_     _|.----..--.--.    |     __|.----.|__|.----..-----..-----..----..-----.
  |   |  |   _||  |  |    |__     ||  __||  ||  __||  -__||     ||  __||  -__|
  |___|  |__|  |___  |    |_______||____||__||____||_____||__|__||____||_____|
               |_____|     `cat /etc/redhat-release`" 

echo -e "${BROWN}
 //- CPU       ...........: $LOAD1, $LOAD5, $LOAD15 (1, 5, 15 min)
 //- Memory    ...........: $MEMORY1 / $MEMORY2
 //- Processes ...........: $PSA running
 //- SysUptime ...........: $upDays days $upHours hours $upMins minutes $upSecs seconds
 //- Disk      ...........: $ROOT remaining ${NC}
"
