#!/usr/bin/env bash

#set -ex

GREEN='\033[32m'
BROWN='\033[36m'
NC='\033[0m'

function info() {
    echo -e "${GREEN}$1 ........ [${BROWN}$2${GREEN}]${NC}"
}

function flowam() {
    sudo ipsec auto --route flowam
    sudo xl2tpd-control connect flowam
    info "=>>> ${1} VPN connect " "✔"
    for i in $(seq 9); do 
        if ifconfig -s | grep ^ppp0; then
            sudo route del 1.0.0.1 ppp0
            sudo route add -net 10.0.0.0/14 ppp0
            info "=>>> VPN online  " "✔"
            exit 0 
        else 
            sleep 1 
            echo -ne "$i.."
        fi 
    done 
    info " ${1} VPN (via ppp0) not up yet" "✖"
}

function home() {
    sudo ipsec auto --route home
    sudo xl2tpd-control connect home
    info "=>>> ${1} VPN connect " "✔"
    for i in $(seq 12); do
        if ifconfig -s | grep ^ppp1; then
            sudo route del 1.0.0.1 ppp1
            sudo route add -net 172.0.0.0/14 ppp1
            info "=>>> ${1} VPN online  " "✔"
            exit 0
        else
            sleep 1
            echo -ne "$i.."
        fi
    done
    info " ${1} VPN (via ppp1) not up yet" "✖"
}

function disconnect() {
    sudo xl2tpd-control disconnect $1
    info "=>>> VPN ${1} offline " "✔"
}


while :; do
    case $1 in
        home)
            home
            break
            ;;
        flowam)
            flowam
            break
            ;;
        off)
            disconnect "${2}"
            break
            ;;
        *)
            break
    esac
    shift
done
