#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.xmonad/bin

# Configure X
sudo xset r rate 250 60
xmodmap $HOME/modmap.file
#xsetroot -cursor_name left_ptr &
#setxkbmap -option "ctrl:nocaps" &
ibus-daemon --xim -r -d

# Start a window compositor. This ensures Google Chrome paints correctly.
#xcompmgr -n &

# Start the system tray
#tray &

# Start two terminals
gnome-terminal &
#gnome-terminal &

# Start a browser
#google-chrome &

# Start sound server
#pulseaudio --start --log-target=syslog &

#gnome-session &
